language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install .
  - pip install pytest==2.9.2
  - pip install coverage
  - pip install coveralls
script:
  - coverage run --source chainsmoke -m py.test
  - coverage report
after_success:
  - coveralls
